### PR TITLE
Protocol for join-along

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Making a protocol for join-along as outlined in: issue #172.

I have not had a chance to take a look at the compliance tests related to join/join-along. But I should be able to at some point.

### CODE REVIEW

**Comment by mikera** [comment]
Looks good! Any reason why we can't support joining along arbitrary dimensions? 

I think the same code might actually work for any dimension?

**Comment by Tim-Brooks** [comment]
If there is more than one column and you try to join along the third dimension:

(mp/join-along [[[1 2] [3 4]] [[2 3] [4 5]]] [[[6] [8]] [[9] [10]]] 2) = [[[1 2 6] [2 3 9]] [[3 4 8] [4 5 10]]]

The columns get messed up.

Obviously it should be possible to support arbitrary dimensions. I just have not spent enough time to look into what needs to be changed for that to happen.

I still need to get more familiar with the entire core.matrix api. It is possible there are other functions that could make writing this join-along arbitrary dimensions easy.

**Comment by mikera** [comment]
@tbrooks8 ah I figured out a way to do it.... see https://github.com/mikera/core.matrix/commit/f83678c5d3000a392573a8613adc5bdf79cceac6

**Comment by Tim-Brooks** [comment]
Oh cool. I thought there had to be some small change that would make it work.

**Pull request merged**
