### PR TITLE
Completed the diagonal function and added tests.

### PR DESCRIPTION
**Pull request by prasant94**
I changed the code to use `cond` and the function returns an empty vector for values of k that are out of range

### CODE REVIEW

**Comment by mikera** [comment]
Looks good - though we probably need to have a bit more discussion about the return values.

`nil` might be a better for positions that are completely out of range? nil has the advantage that it can be used in conditional tests etc.

e.g. diagonals of `[[1 2] [3 4]]` would be

```
0 => [1 4]
1 => [3]
2 => [] (or nil?)
3 => nil
4 => nil
```

**Comment by mikera** [comment]
I will merge this anyway, as it is better than what we currently have

**Comment by prasant94** [comment]
`2 => nil` makes more sense?

**Comment by mikera** [comment]
Not sure to be honest...

The Issue is around writing generic algorithms - does it make sense to interpret 2 as a length 0 vector for algorithms that work over some arbitrary set of diagonals? If that algorithm needs vectors, then a length 0 vector is probably a better return value (nil isn't considered as a length 0 vector, although it can be cast to one....)

Possibly worth asking the Google Group?

**Comment by prasant94** [comment]
ok

**Pull request merged**
