### PR TITLE
Add is-matrix?

### PR DESCRIPTION
**Pull request by siscia**
I am not sure if it is a good design choice, however I think it may be very handy to have a function that return if the object is something we are suppose to handle in some way or if it is nothing...

I found it helpful with assign! for instance...

### CODE REVIEW

**Comment by mikera** [comment]
Hmmmm how does this improve on the existing `matrix?` or `array?` functions in clojure.core.matrix?

Is it intended to test specifically for matrices of dimensionality 2? If so then I can see some value but then:
- The docstring needs to say this, so that implementers know exactly what to do
- It should probably be in a separate (optional) protocol so that it minimises the mandatory list of protocol functions
- There needs to be a default implementation, presumably something like `(and (array? m) (== 2 (dimensionality m)))`

**Comment by siscia** [comment]
My ideas was to give an easy way to define if something belong to the clojure.core.matrix ecosystem.

I guess is-matrix? is the wrong name, but I think it might be useful...

You see what I mean ?

**Comment by mikera** [comment]
`array?` should already do this.

**Comment by siscia** [comment]
Yes it does, and it does even in a better way that is-matrix? could do...

Sorry about that

**Pull request closed without merging**
