### PR TITLE
Select-rows

### PR DESCRIPTION
**Pull request by Gerrrr**

### CODE REVIEW

**Comment by mikera** [comment]
Comments:
- Some build failure?
- Looks like "rows" argument can be either number or collection in `selecty-rows`. Not sure I'm comfortable with this: seems like unnecessary type overloading?
- The `dataset` constructor seems to be using the rows of the matrix as the columns of the dataset. This isn't what I would expect... can we review this?

**Comment by Gerrrr** [comment]
Thanks for the detailed feedback. I fixed all the issues you mentioned.

**Comment by mikera** [comment]
Still not sure about the `dataset` constructor doing a transpose of a matrix.

This seems wrong to me... I'd expect the rows of a matrix to become the rows of the dataset. Is there a reason you are doing the other way round?

**Comment by Gerrrr** [comment]
I added new constructor dataset constructor - `(dataset column-names seq of row maps)`.
It is pretty handy in a lot of cases when you want to create dataset from row maps, but you want to specify order of columns. It is also used in `select-rows` for final dataset creation.

**Comment by mikera** [comment]
Sounds reasonable.

I still think you need to fix the transpose issue! (or convince me that there is a good reason to do it this way...)

**Comment by Gerrrr** [comment]
Can you please describe transpose issue in more details? 
`select-rows` now creates dataset from row-maps which actually creates it from array and renames the columns.

**Comment by mikera** [comment]
Sure - I think the `dataset` constructor should take the slices of the source array as rows, not columns, i.e.

``` clojure
(dataset [:name :age] [["Bob" 42] ["Anne" 37] ["Charlie" 46]])
```

Currently it looks like you need to specify the source array in a transposed form, i.e. the rows of the source array become the columns of the dataset. This feels wrong to me.

**Comment by mikera** [comment]
Looks good! Think you just have a conflict to resolve first then I will merge

**Comment by mikera** [comment]
@Gerrrr able to fix this today? Hoping to do a core.matrix release, would be good to get this merged in first.....

**Pull request merged**
