### PR TITLE
Primitive NDArray support

### PR DESCRIPTION
**Pull request by si14**
This PR contains primitive NDArray support with matrix multiplication implementation as a proof that primitive NDArray can be close to Vectorz performance-wise.

### CODE REVIEW

**Comment by mikera** [comment]
Looks good - but I don't see any new tests.

Do we have test coverage of all the new types?

**Comment by si14** [comment]
Ooops, I was going to add tests to the branch before merge :) OK, I'll just push them to develop.

**Comment by si14** [comment]
BTW, do you have any comments on that "magic" stuff in ndarray.clj? I think it's better than straightforward "eval" as in protocols.clj:441.

**Comment by mikera** [comment]
I tested it and it seemed to be working fine so I just merged it.

More tests welcome of course!

The magic macro stuff looks good - seems pretty clear what it is doing, I like the init-magic map as a way of specifying the replaceable parts, and I like the way that you can specify exactly which types each part gets extended to.

**Pull request merged**
