### PR TITLE
use clojure 1.5 & euclidean distance.

### PR DESCRIPTION
**Pull request by grtlr**
Added the latest release of `clojure 1.5` to the `project.clj`.
Implemented the euclidean distance between 2 vectors.

### CODE REVIEW

**Comment by mikera** [comment]
Lots of good stuff, here, I like the distance function.

Just have a couple of comments before we merge this that would be good to address:
1. I think we should hold back and stick with 1.4 at the moment: we need to be conservative with version requirements as much as possible. I don't yet see anything in core.matrix that needs 1.5 at present. Arguable we should even try to make core.matrix work with 1.3.
2. Perhaps distance should be a separate protocol, e.g. PVectorDistance? In general, it helps to keep the protocols as fine-grained as we can because a) it makes it easier for implementation to select a subset of functionality to implement and b) it reduces breakage for people who have implemented the old version of the protocol

**Comment by grtlr** [comment]
I refactored the distance function into its own protocol `PVectorDistance`. I think I'm also getting a better understanding of how the protocol mechanism works. I reverted back to `clojure 1.4` so you can easily merge it with the `develop` branch.

**Comment by mikera** [comment]
Merged, thanks!

**Comment by mikera** [comment]
P.S. had to do a quick fix on the default implementation, for cases where the vector isn't a sequable object. In general, the default implementations can't assume much about their parameters other then that they implement the core.matrix protocols.

See:
- https://github.com/mikera/matrix-api/commit/44ddfb69e5736170e29d865d972e82e281298b84

**Pull request merged**
