### PR TITLE
Implement condition number

### PR DESCRIPTION
**Pull request by fyquah**
Implements feature #242

### CODE REVIEW

**Comment by mikera** [comment]
This looks sensible, but can you add a few tests to verify that it is working correctly?

You'll probably need to test using an implementation such as `:vectorz` which has a SVD implementation.

Also, can you confirm that you have a Clojure CA?

Thanks!

**Comment by fyquah** [comment]
Should i write a `condition-number` protocol in `core.matrix` and implement it a `:vectorz` instead then? (For consistency with other linear functions).

I do have a CA.

**Comment by mikera** [comment]
OK thanks

You don't need to write a specific vectorz implementation: the SVD implementation should do all the work for you.

It just needs some tests that verify that the condition number comes out as expected for some sample matrices. You should be able to do something like `(condition-number (array :vectorz [[....]]))` and test that the result comes out as expected for a few different test matrices.

**Comment by fyquah** [comment]
Written the tests, i have tested those values with GNU octave, so they should be alright.

Some questions:
- does `core.matrix` has a built-in `approx=` function? That would seem really useful for various use cases.
- Is SVD meant not to work on vectors? (ie: the class `mikera.vectorz.Vector`)

**Comment by mikera** [comment]
There is an extra arity of `equals` that allows you to specify precision for comparison.

I'haven't about SVD for vectors. What behaviour do you expect to see?

**Comment by fyquah** [comment]
I'd expect it to behave exactly like `(svd (matrix [ [1 2 3] ]))` , which will always output `1` , since there is only one eigenvector.

I'd expect the svd behaviour to be an issue under `vectorz-clj` / `vectorz` ?

**Comment by fyquah** [comment]
The patch should be alright now.

**Comment by mikera** [comment]
OK great, thanks!

**Comment by mikera** [comment]
Regarding SVD on a vector, I'm not convinced it really makes sense. In `core.matrix`, we generally treat vectors differently from 1xN matrices, so I don't think the SVD operation is well-defined on a vector.

See: https://github.com/mikera/core.matrix/wiki/Vectors-vs.-matrices

**Pull request merged**
