### PR TITLE
Fix ndarray-double matrixops return vals

### PR DESCRIPTION
**Pull request by dmarjenburgh**
ndarray-double's inverse and determinant were calling `lu-decompose!`, which throws IllegalArgumentExceptions on singular input.

This change moves the code to an internal ns use fn `_lu-decompose!` and now throws ex-info with `{:cause ::singular}`.
The functions `lu-decompose!`, `determinant` and `inverse` now call the internal `_lu-decompose!` in a try block and return the appropriate return values (nil for inverse and lu, 0 for determinant) when ex-info is caught with :cause ::singular

There were also two small tests added that are passing from this change

### CODE REVIEW

**Comment by dmarjenburgh** [comment]
Related discussion: #38

**Comment by dmarjenburgh** [comment]
Alternatively lu-decomposition! can return nil and determinant/invert will have nil checks. Which one is preferable?

**Comment by mikera** [comment]
I think it would be best to return nil (indicating no result) for lu-decompose with singular matrices. Otherwise calling code needs to catch exceptions.

I quite like the idiom `(or (lu-decompose ....) ......)`

**Comment by dmarjenburgh** [comment]
I've tried to change the structure as little as possible. I assume the code was optimised for performance by avoiding function call overhead., but it makes it a little hard to read. There may be ways it can be both improved and cleaned-up with direct-linking for example, but I'll leave that for another PR after I have some metrics going.

**Comment by mikera** [comment]
OK thanks, looks good and it's great that you have the tests there. Will merge this in for now, do send another PR if you make some further improvements.

Thanks!

**Pull request merged**
