### PR TITLE
added sorting function + protocol + default implementation + tests

### PR DESCRIPTION
**Pull request by prasant94**
sorts all slices of any multi dimensional array.

``` clojure
(deftest test-sort-array
 (is (= [1 2 3 4 5 6 7 8] (sort-array [1 3 5 7 2 4 6 8])))
 (is (= [1 2 3 4 5 6 7 8] (sort-array [1 2 3 4 5 6 7 8])))
 (is (= [1 2 3 4 5 6 7 8] (sort-array [8 7 6 5 4 3 2 1])))
 (is (= [1 2 3 4 5 6 7 8] (sort-array [1 3 5 7 2 4 6 8] 'asc)))
 (is (= [8 7 6 5 4 3 2 1] (sort-array [1 3 5 7 2 4 6 8] 'desc)))
 (is (= [8 7 6 5 4 3 2 1] (sort-array [1 2 3 4 5 6 7 8] 'desc)))
 (is (= [8 7 6 5 4 3 2 1] (sort-array [8 7 6 5 4 3 2 1] 'desc)))
 (is (= [[8 7 6 5] [4 3 2 1]] (sort-array [[8 5 7 6] [1 2 3 4]] 'desc))))
```

### CODE REVIEW

**Comment by mikera** [comment]
Hi Prasant. 

This sorting functionality is a really good idea, though there this needs more discussion on the API first before we merge anything in. Getting the API right up front is very important.

There are quite a few considerations:
- How does this fit / compose with existing Clojure sorting functions?
- should we be using symbols for asc and desc? Or keywords? Or generic comparators?
- what about sorting be specific dimensions?
- what about sorting according to a specific row?

Can you make a proposal / request for comments on the Google Group?

**Comment by astanin** [comment]
I wonder what backends can do it efficiently (faster than Clojure sort functions)?

I expect that an immutable sort will perform similarly to the existing Clojure functions.
I don't know which existing or potential core.matrix backends implement fast in-place sorting.

Please note that Python's [numpy.sort](http://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html) supports sorting along arbitrary axis and allows to choose sorting algorithm (trade space complexity vs stability).

**Comment by prasant94** [comment]
I am thinking we could use the inbuilt function to sort the 1D arrays. But we'll need a new implementation if we sort along a different dimension.
By sorting according to a specific row, you mean sorting a matrix right? Or does it apply to n dimensional arrays too?
Should we take a function as a parameter like comparators in java to compare two elements? Then a user can sort in any way they like.

Yes, sorting does take way too much space in clojure. Is there a way to make it more efficient?

**Comment by mikera** [comment]
Vectorz has the potential for some very fast sorting capabilities if you use views: it can sort and re-index a view over existing data in O(N log N) time for an NxN matrix for example - which is considerably faster than O(N ^ 2) which is optimal for a matrix sort that performs copying.

I'd like to ensure that any `core.matrix` sorting API is able to take advantage of these kind of features.

**Comment by mikera** [comment]
See discussion: https://groups.google.com/forum/#!topic/numerical-clojure/FIFkhGN6Sac

**Comment by prasant94** [comment]
So according to the order function discussed on the google group, what will be the output for this?

```
(def a [[[1 7 9]
         [4 6 5]
         [0 3 8]]
        [[0 3 7]
         [7 1 4]
         [8 3 1]]
        [[3 5 8]
         [4 8 1]
         [6 5 3]]]

(order a 1 0)
(order a 2 1)
(order a 0 2)
```

**Comment by mikera** [comment]
Probably an error?

For a 3D array, I think you would need to either:
-  "fix" two dimensions so that comparison takes place over a single 1D array of numerical values  
- provide a custom comparator that compares multi-dimensional objects.

The last case sounds fancy but isn't all that rare: I've seen quite a few cases where you want to sort a list of vectors by the dot product with some other fixed vector.

**Comment by prasant94** [comment]
How about this order function:

``` clojure
(defn order
  ([m]
    (order m <))
  ([m com]
    (cond 
      (mp/is-scalar? m) (error "Can't compute sort order for scalar")
      (> 1 (mp/dimensionality m)) (error "Insufficient number of arguments")
      :else (let [aux (fn [m c] (into [] (sort-by (fn [i] (m i)) c (range (mp/dimension-count m 0)))))]
                (aux (aux m com) <))))
  ([m dim elem]
    (order m dim elem <))
  ([m dim elem com]
    (let [sort-keys (cond
                      (== dim 0) (mp/get-column m elem)   ;along column
                      (== dim 1) (mp/get-row    m elem)   ;along row
                      :else      (error "dimension can be either 0(for column) or 1(for row)"))]
          (order sort-keys com))))
```

tests:

``` clojure
user=> (def a [6 4 9 2 5])
#'user/a
user=> (order a)
[3 1 4 0 2]
user=> (order a <)
[3 1 4 0 2]
user=> (order a >)
[1 3 0 4 2]
user=> (def A [[1 3 2]
  #_=>         [4 1 3]
  #_=>         [1 2 5]])
#'user/A
user=> (order A 1 0)
[0 2 1]
user=> (order A 1 1)
[2 0 1]
user=> (order A 0 2)
[0 1 2]
user=> (order A 1 0 <)
[0 2 1]
user=> (order A 1 1 <)
[2 0 1]
user=> (order A 0 2 <)
[0 1 2]
user=> (order A 1 0 >)
[2 0 1]
user=> (order A 1 1 >)
[0 2 1]
user=> (order A 0 2 >)
[2 1 0]
```

It only works for the first 2 dimensions.

**Comment by mikera** [comment]
Hi Prasant,

There is some good stuff here, but I think the API design needs more discussion. In particular, I don't think the `order` function should take a comparator: the idea is to do re-ordering independent of how the order is produced (which might be by a comparator, or might be by another approach...)

I think this discussion needs to happen on the Google Group, not in PR comments. Not enough people will see comments here unless they follow this issue.

Can you perhaps put the API proposal on the Wiki perhaps: https://github.com/mikera/core.matrix/wiki/Sorting

And then send a request for comments to the Google Group?

**Comment by mikera** [comment]
Hi Prasant,

Any further thoughts on this? I'm inclined to close this PR until we have consensus around a consistent design and a PR that reflects this....

  Mike.

**Comment by prasant94** [comment]
Sorry, I have been really busy with college stuff. I will start again after a couple of weeks.

Also, shouldn't the order be according to some rule the user can define? Otherwise it'll only be increasing order of values.

**Comment by prasant94** [comment]
and yes, lets close this discussion, we can discuss the API on the google group

**Pull request closed without merging**
