### PR TITLE
#86 pow support for array exponents

### PR DESCRIPTION
**Pull request by luxbock**
Addressing #86

### CODE REVIEW

**Comment by luxbock** [comment]
I see that I should send the Clojure CA for this to be accepted, so I will do that as well.

**Comment by mikera** [comment]
Looks good. Can you add a test case?

Let me know when you have sent off the signed CA and I'll merge it in.

**Comment by luxbock** [comment]
I have submitted the CA.

**Comment by mikera** [comment]
Great, thanks for the contribution! 

I've merged it in now, will have a quick experiment to make sure we haven't missed any edge cases but it all looks good so far.

**Pull request merged**
