### PR TITLE
completed proposed selector implementation

### PR DESCRIPTION
**Pull request by mschuene**
The functions sel, sel-set and sel-set! are now feature complete and based on protocols.
Default implementation dispatches to lower-level protocol and uses get/set column/row when possible
I will post an overview over the implemented functionality for discussion to the numerical clojure group in the next days.

### CODE REVIEW

**Comment by mikera** [comment]
Think you have some merge conflicts to resolve?

**Comment by mschuene** [comment]
fixed the merge conflict

**Comment by mikera** [comment]
Hmmmm there is quite a lot of stuff here, including new protocols. I'm hesitant to merge all this before we've got more clarity on the right API. 

Particular points that aren't obvious to me:
- It touches the protocols - is this really needed? Why can't we implement selections on top of the current protocols?
- Why do these specific set-selection functions need protocols? Are they really special in some way, or are there more generic array modifying capabilities that we should support instead?
- Introduces new magic vales like `:*`. We really need to figure a comprehensive list of these and consistent definitions
- How do selections interact with views, e.g. the ones provided by Vectorz?
- How does this interact with presence / absence of array mutability?
- How do we propose to handle operations other than setting, e.g. applying `abs` to a selection?

It would be good if we could address these in the Wiki / discussions on Google Groups

**Comment by mschuene** [comment]
I detailed the implementation on the google group
https://groups.google.com/forum/#!topic/numerical-clojure/zFjIl8zgX6M

**Comment by mikera** [comment]
Cool thanks Maik I added some comments there as well

**Comment by mschuene** [comment]
I updated the pull request according to the discussion in the mailing list. Changes:
- data only selection functions are added to clojure.core.matrix namespace, the clojure.core.matrix.select namespace functions are build ontop of them (on top of the same protocols)
- select is guaranteed to return a view
- An Index can be either a number or any 1-d core.matrix array
- simplified protocol functions
  - only accept 1-d core.matrix arrays as indices
  - removed the linear-... protocol functions.
- updated tests and documentation
- added set-1d!, set-2d!, set-nd! protocol function implementations to NDWrapper
- set-selection! is now just (assign! (select a args) vals

**Comment by mikera** [comment]
Looks great, thanks Maik!

**Pull request merged**
