### PR TITLE
Implement emap-indexed as suggested in #202

### PR DESCRIPTION
**Pull request by japonophile**
This is an initial implementation of emap-indexed.

When adding tests, I found some other issues:
- found and fixed an issue with object-array implementation of emap: it was not working with 3 or more parameters.
- found an issue in with sequence implementation of emap (broadcast-compatible throws an exception), but wasn't able to fix it.

### CODE REVIEW

**Comment by mikera** [comment]
Look promising.

Some initial thoughts:
- Can you separate the new protocol functions into a separate protocol? If we don't do this, then old implementations tend to break beacuse Clojure doesn't like partial implementations of protocols
- What is performance like? I think it would be useful to demonstrate a performance win or at least parity vs. simply iterating over elements.
- Does it work if you use int-arrays or long-arrays as indices? If so that could be helpful in many circumstances, since you can simply mutate the index array and pass it in multiple times to the function
- Can you also separate out the object-array fixes? I'd rather merge fixes in quickly, whereas we need a bit more consideration of API changes

Thanks!

  Mike.

**Comment by japonophile** [comment]
Thanks for the feedback, Mike.
Let me first separate the object-array fix.
Then I'll address your comments.

**Comment by japonophile** [comment]
1) I have made the easy change: extracted the new functions into a separate protocol.

2) Regarding performance, it depends on the particular implementation.  However, I don't see how emap-indexed could be faster than emap, because if it would be, we could just implement emap the same way and ignore the index. As an example, I measured the performance for a 10x10 persistent vector doing a map of the identity function (for emap-indexed, the index vector is just ignored). Criterium gave 22μs for emap vs 97μs for emap-indexed.  After making some change, I could get it down to 58μs (see below).

user=> (require '[clojure.core.matrix :as m])
user=> (require '[criterium.core :as c])
user=> (def a (m/matrix (vec (for [i (range 10)](vec %28for [j %28range 10%29] %28rand%29%29)))))

user=> (c/bench (m/emap (fn [x] x) a))
Evaluation count : 2698560 in 60 samples of 44976 calls.
             Execution time mean : 22.214940 µs
    Execution time std-deviation : 192.916383 ns
   Execution time lower quantile : 21.918464 µs ( 2.5%)
   Execution time upper quantile : 22.624147 µs (97.5%)
                   Overhead used : 12.202769 ns

user=> (c/bench (m/emap-indexed (fn [v x] x) a))
Evaluation count : 1045140 in 60 samples of 17419 calls.
             Execution time mean : 58.442503 µs
    Execution time std-deviation : 769.751303 ns
   Execution time lower quantile : 57.494394 µs ( 2.5%)
   Execution time upper quantile : 59.941964 µs (97.5%)
                   Overhead used : 12.135980 ns

Similar analysis could be done for other implementations, and maybe some optimisations would be possible in some cases.

3) As for using int-arrays or long-arrays as indices, it may be possible, but due to the recursive definition of emap-indexed (like emap), we end up cons-ing the current index onto the existing indices vector when passing it to the map function.  If we restrict ourselves to homogeneous matrices (e.g. made only of persistent vectors, or only of double arrays), then we could create vectors of indices upfront by not having to call emap-indexed recursively.
In fact, assuming homogeneous matrices also would allow to improve performance.  For example, I was able to get the benchmark above down to 37μs assuming 2D nested persistent vectors.  But this would break the generality of the current implementation.

Let me know your thoughts.

**Comment by mikera** [comment]
OK this looks good, I will merge it in for now and have an experiment but I think it looks sounds and the performance seems decent enough.

On 3), my main concern is that implementations which are tuned for performance (e.g. `vectorz-clj`) can use int arrays if they want to. For the default implementation, I think regular Clojure data structures as indices are fine.

**Pull request merged**
