### PR TITLE
dataset conj-columns implemented

### PR DESCRIPTION
**Pull request by Gerrrr**

### CODE REVIEW

**Comment by mikera** [comment]
Should this be called `merge-columns` perhaps? What is the behaviour on duplicate column names?

**Comment by Gerrrr** [comment]
You are right, we already have `merge-datasets` (https://github.com/mikera/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix/dataset.clj#L112), so probably that one is redundant. 
Although, the difference from `merge-datasets` is that `conj-columns` fails on duplicate column names.

**Comment by mikera** [comment]
If it is about concatenating columns, perhaps `join-columns` is better - as an analogy with `join` and `join-along` in the main core.matrix API?

**Comment by Gerrrr** [comment]
Good idea. How about to rename also `conj-rows` into `join-rows`?

**Comment by mikera** [comment]
Yeah looks good!

**Pull request merged**
