### PR TITLE
Cljc

### PR DESCRIPTION
**Pull request by rosejn**
This PR gets core.matrix running in Clojurescript.  All previous tests for Clojure still pass using "mvn test", and a minimal set of Clojurescript tests are in src/test/cljs.

The only known issue is around the implementations.  Clojurescript doesn't have alter-var-root, and I'm not clear enough on how this system is used to come up with a good solution yet.

It would be great to get some more people trying this out and expanding the protocol coverage onto JS types.

### CODE REVIEW

**Comment by mikera** [comment]
Looks like an impressive piece of work - well done Jeff!

It's currently breaking the Travis CI build, seemingly due to use of a vectorz-clj snapshot. Is this necessary? Do we need a new vectorz-clj release or does the current 0.38.0 do the trick?

**Comment by mikera** [comment]
Don't worry I think I fixed this. Had to add some macros back into c.c.m.utils in order to maintain backward compatibility with vectorz-clj

**Comment by rosejn** [comment]
Oh yeah, I forgot to mention the other libs.

https://github.com/thinktopic/vectorz-clj - with the macro changes

https://github.com/thinktopic/ndarray/tree/matrix

He develops ndarray inside emacs org mode files that have to be
post-processed to output a Clojure project.  I don't use emacs so that is a
bit awkward.  The branch above has the core.matrix implementation
integrated in the Babel (generated) directory.  In the end it was just
adding the protocols to the main macro that he uses for code generation to
support all varieties of typed array.  It might actually be nice to use for
Clojure too, giving support for more than just double matrices.  I've
wanted bytes and booleans before...

**Comment by mikera** [comment]
Is there a reason that we need to move macros to a separate namespace? It would be a breaking change on the API front.....

**Comment by rosejn** [comment]
Shoot.  I didn't think libs were supposed to use that stuff.  In Clojurescript you have to use require-macros to refer to macros, so it makes it more straightforward to use the reader macros if you split it out.  I also didn't know how to have two different versions of a macro that should expand differently depending on whether you are in Clojure or Clojurescript.  That's why I broke out some of them in a separate file.

**Comment by mikera** [comment]
Possibly libs shouldn't.... though vectorz-clj does right now and the change breaks it. I think we maybe need to be more explicit which namespaces are considered public i.e. vs. experimental vs. private in general :-)

I'm OK with a breaking change if there is good reason, of course, assuming we want to argue that all the util stuff should be considered private implementation detail. right now it's not too hard to fix all the dependencies.

**Pull request merged**
