### PR TITLE
Little change for protocols.

### PR DESCRIPTION
**Pull request by siscia**
Little change in the protocol, now the mutable setter are called with a ! and I changed the name of the protocol to make it clear that it is for mutable structure.

Also add protocol for setter in case of immutable structure

### CODE REVIEW

**Comment by mikera** [comment]
Looks sensible to me. 

Happy to merge but you need to have a signed Clojure CA - do you have one?
- http://clojure.org/contributing

**Comment by siscia** [comment]
No I do not... I signed one here at home... I need to MAIL it to Rich ? An pdf by E-mail is not enough ?

Living in Italy it would take long time...

**Comment by mikera** [comment]
Yeah I think you need to mail it. 

Some limitation of the US legal system I think..... there are lots of places where electronic copies aren't considered valid and I think copyright arrangements are one of these. Or something like that.

**Comment by siscia** [comment]
Ok, I see, I will mail it ASAP.

In the mean while (since it wil take at least 2/3 weeks) if you wanna go ahead and push you the same modification it's fine for me... I agreed and I release the code under the Do Whatever You Want license...

**Comment by mikera** [comment]
Cool, thanks for doing that!

I still don't think we can accept anything under the "do whatever you want" license unfortunately.

Also your patch now doesn't apply cleanly. I suggest you update once the CA comes through.

**Comment by mjwillson** [comment]
This CA stuff seems a bit of a pain if the postal bureaucracy is going to hold up merging people's individual contributions at this early stage.

Perhaps we can have a shared fork which we use to merge everyone's work for now, and leave mike's repo as the official could-in-theory-be-contributed-to-clojure-core version which stuff gets pulled into once people are signed off?

**Comment by siscia** [comment]
I just send my CA, it will take about 2/3 weeks...

@mjwillson Hum... I like the idea... We can make a fork for everybody who don't have a CA yet, and when the CA is ready merge it back together...

**Comment by mikera** [comment]
As long as everyone agrees to sign a CA I think it's fine. I'm happy to accept pull requests on the assumption that everyone is getting their CA sorted out.

The risk is someone refusing to get a CA: but
- That would be pretty unreasonable so I don't think it is likely. Everyone here seems pretty decent.
- We can just back out all their commits and rewrite. Annoying, but not a killer

**Comment by mikera** [comment]
Hi Simone, I see your CA has come through now.

What do you want to do with this one? it doesn't merge cleanly right now, but happy to merge if you fix it up.

**Comment by siscia** [comment]
Ok, I will fix it asap... I guess in about 2-3 hours

**Comment by siscia** [comment]
You should be able to merge it now...

If not, it is possible that I messed up something, if so just close this pull request, I will make a new one.

**Comment by mikera** [comment]
Hmmm GitHub is still saying that the pull request cannot be merged. Did you merge in the latest master version before pushing it out to your repo? There are quite a lot of changes in master that I suspect are causing merge conflicts.

**Comment by siscia** [comment]
Sorry, I am having some issue... I mean if you want to just modify the code by yourself is fine for me, it will be easier and faster.

**Comment by mikera** [comment]
Your call. But it's a good idea to learn how to use the git tools if you get a chance..... you need to fetch from the latest master to your local repo, merge into your local branch, then push to your github repo. 

That way all the latest changes will be merged into your branch at the time you issue the pull request.

**Comment by heffalump** [comment]
Simone: have you configured your remotes correctly?  I think you might be having trouble with pulling in the changes on the upstream repo (that would be mikera/matrix-api).  It's laid out in https://help.github.com/articles/fork-a-repo

The relevant part is step 3.  You've cloned your fork, so on your machine origin points to that fork.  So when you do  say:

**git pull origin master**

you're pulling from your own fork.  But you need to pull from the parent, so you need to set the upstream remote first (if you haven't already):

**git remote add upstream https://github.com/mikera/matrix-api.git**

then you pull in the changes:

**git pull upstream master**

(it is master we want, right mike?  I'm not sure what's going on in the develop branch)

then you fix any conflicts on your local machine.  When you're done, it passes all the tests, etc.

**git push origin master**

pushes the work to your own fork, then you reissue the pull request.  I hope this helps.

**Comment by siscia** [comment]
@Heffalump, yeah it really helped, thanks so much...

Now it SHOULD work a clean merge...
I didn't add test thought

**Comment by mikera** [comment]
OK this looks good.

In future I suggest we try to make changes against the develop branch? It's probably roughly a good idea to follow the "git-flow" approach:

http://nvie.com/posts/a-successful-git-branching-model/

**Comment by mikera** [comment]
Can I just check: the idea of the "set-1d" methods is that they return a new matrix right? In that case they should work for any matrix, but for a mutable matrix they should return an updated deep clone?

Asking because we need compliance tests to check the behaviour in implementations.....

**Comment by siscia** [comment]
Yes you right.

However i would say the other way around: "set-1/2/nd **!** " return the same matrix with some modification, if and only if we are calling it on mutable matrix, if we call it on immutable structure they should either don't be implemented or raise an exception.

We decide that the standard was immutable structure, don't we ?

**Comment by mikera** [comment]
If called on an immutable structure, set-Xd! should throw an exception I think. I've added a compliance test to check this in the latest "develop" branch

**Pull request merged**
