### PR TITLE
Pretty printing enhancement

### PR DESCRIPTION
**Pull request by grtlr**
I started to implement the pretty printing of matrices. I have to admit I still get a little bit lost in the _matrix-api_ project. Because of this I wasn't able to test the functions in the context of the whole project and I don't quite see the best way to incorporate it. It would be really great if you could take a look at it. Thank you very much.

### CODE REVIEW

**Comment by mikera** [comment]
Hi there,

The problem seems to be that there is a cyclic load dependency: pm is in `clojure.core.matrix` which depends on `clojure.core.matrix.printing` which depends back on `clojure.core.matrix`

I think there are two solutions that make sense:
1. put all the printing code in `clojure.core.matrix` itself
2. make `clojure.core.matrix.printing` depend on `clojure.core.matrix.protocols` instead (this is the approach used by the various default implementations e.g. `clojure.core.matrix.impl.persistent-vector`). This is a little more complex since it means you need to call the protocol functions directly and can't use some of the helpful convenience functions in `clojure.core.matrix`

Either of these approaches should work fine.

**Comment by grtlr** [comment]
Ok, that makes sense. :) I think as long as the code for _pretty-printing_ doesn't get more complex, it should be good enough to put it in `clojure.core.matrix`. I will make those adjustments and re-commit them.

**Comment by mikera** [comment]
Great, thanks!

By the way do you have a Clojure CA signed?

**Comment by grtlr** [comment]
I have the CA printed out and will send it away in the next couple of days.

**Comment by mikera** [comment]
Cool, `pm` seems to be working nicely!

**Pull request merged**
