### PR TITLE
symmetric? initial version

### PR DESCRIPTION
**Pull request by mars0i**
Let me know if something's not right.  Thanks!

### CODE REVIEW

**Comment by mikera** [comment]
hmmm Travis build seems to be broken: https://travis-ci.org/mikera/core.matrix/jobs/16161041

The pom.xml seems to have been significantly changed - is this intentional? In particular it looks like lein has auto-generated the pom, which isn't good: we use mvn as the official build tool for core.matrix (as with other Clojure contrib libraries) 

I suspect this is what is causing the problem. I think you may need to revert back to the original pom.xml and only make targeted changes (if these are even necessary). Developing using lein is fine of course, but please don't nuke the official pom!

**Comment by mikera** [comment]
Most of the other code looks good to me on inspection - should be good to merge provided we can get the build fixed.

**Comment by mars0i** [comment]
I don't use pom.xml; yes, it's autogenerated by clojars.  I didn't know it would all be run through a CI system (and just learned what "CI" means).   Just feeling my way here .... Since I don't really understand Leiningen, and, uh, hate monkeying with Java classpaths (bad experiences with multiple library versions back in my Java programming days), I've been integrating my vectorz-clj and core.matrix via clojars--lein deploy, lein deps.  I'm sure there's a better way.  I don't  understand why I have my own pom.xml, though.  When I did 'git pull parent develop' from github/mikera, git didn't complain at all.

Glad the code all looks good!  Happy to be able contribute, despite my newbness.

From your latest comment (on the vectorz-clj pull req), it sounds like I should just wait until the new release, and then copy the main pom.xml and project.clj files, or start with fresh clones and then apply my patches to it.  Does that make sense?  Thanks.

**Comment by mikera** [comment]
Hmmm I think the problem is doing the `lein deploy` stuff. I think this auto-generates a pom.xml from the project.clj. This is a complexity that we won't have if we get the new core.matrix release done first, so I suggest that should be the priority - no need to worry about making interim releases until then.

Your approach to fixing things up makes sense. There's probably a clever way to do it with git, but I'm not that much of a git expert myself :-)

**Comment by mars0i** [comment]
OK, sounds good.

Yeah, `lein deploy` overwrites pom.xml every time.  I don't know how to stop it.  (it used to create a git merge conflict, but lately it hasn't, and I don't know why.)  I had a different project.clj to try things out, use my own builds, use Clojure 1.5.1, etc.

BTW I know that you don't use project.clj, but since pom.xml won't change very often, I'd volunteer to try to maintain project.clj in sync with it, if that could be helpful.  I end up updating project.clj by hand from your pom.xml anyway (and then I sometimes add changes).

**Comment by mikera** [comment]
Hmmm not sure how to fix that. Does `lein install` do the same? I usually just use Maven rather than lein, but that's because I know it better.

I'm happy to take patches that keep project.clj in sync with the pom.xml - I try to do that myself but sometimes forget :-)

**Comment by mars0i** [comment]
I've been investigating.  `lein install` writes pom.xml, too.  There's another method that works, though.  Put a directory 'checkouts' in one project, containing a link to the other project directory.  Then the first project loads the second, and leaves pom.xml alone.  No need to build jars.

OK, I'll wait until after the release, and then when I notice differences between pom.xml and project.clj, I'll submit a pull request.

**Comment by mikera** [comment]
Hi @mars0i I'm working on a new core.matrix release over this weekend. 

If you want to do a pull request with _only_ the new functions / protocols and tests (i.e. no changes to the pom.xml) then it should be good to go in the next release.

**Comment by mars0i** [comment]
Hi Mike-

Pull request coming.  

Would it be OK if I updated project.clj to reflect the current pom.xml?  (If so, should I leave the version as 0.18.1-SNAPSHOT in the project.clj, or change it to the coming release id?)  If I get to it before you reply, I'll submit a pull request with no changes to project.clj, but it will be easy enough to redo it with the new project.clj.  I've already made a version that updates the current official one from pom.xml.

Also, do you want a pull request for vectorz-clj with `symmetric?` in it, or should I wait?

**Comment by mars0i** [comment]
That's wierd--why does my commit to my repo cause a message here? I didn't intentionally cause that last message.  Worried I did something wrong.

**Comment by mars0i** [comment]
Trying to figure out how this works .... It appears that when I create a new pull request at this point, what it does is to update the old pull request with the new changes.  The diff I see no longer includes pom.xml and project.clj--only the changes for `symmetric?`.  So I think the new pull request is done.  See how it looks at your end.  (That must be related to the "added a commit" message, although that occurred before the "new" pull request.)

**Comment by mikera** [comment]
OK this looks good to me! I'll merge it in. Can you confirm you've got your Clojure CA done?

**Comment by mars0i** [comment]
Re C: Sorry about this Mike, but I'm new to this, and didn't really think about such things.  I can confirm that I am willing to sign the CA and mail it in the next couple of days (today if there's enough ink in my printer cartridge at home).  If there's a way to do it online, I can do that, but it appears not.  You don't have to worry that I'll renege on this commitment, it's done ... logically, so to speak, but it's not actually, yet.  I hope this doesn't mean that you have to delay the release or back out my changes.

**Comment by mikera** [comment]
OK thanks for letting me know. I think the paper way is the only way to do it at present. 

Appreciate if you could get it done soon - not a big deal but it's a requirement for Clojure contrib which core.matrix will hopefully become at some point.

**Pull request merged**
