### PR TITLE
matlab like array indexing

### PR DESCRIPTION
**Pull request by mschuene**
First version of the matlab style array indexing function proposed here: https://groups.google.com/forum/#!topic/numerical-clojure/zFjIl8zgX6M , to discuss the syntax.
Currently only supports getting elements, not setting them. Maybe another method for this would be the best way of adding it.
Supports all of http://www.mathworks.de/company/newsletters/articles/matrix-indexing-in-matlab.html except the setting of the selected indices.

### CODE REVIEW

**Comment by mikera** [comment]
Hi Maik,

I like where this is going, but not sure if we've quite bottomed out the API yet. We should do this before we merge into the public API.

Can you either:
- put it in the clojure.core.matrix.experimental namespace 
- have a separate "selectors" branch separate from develop.

**Comment by mschuene** [comment]
Hi, I created a new branch selector in my fork and moved the selector functions to a new namespace clojure.core.matrix.select. It seems github doesn't let me do a pull request which would create a new branch. Can you merge it in if you think it is okay?

**Comment by mikera** [comment]
That sounds fine to me... but did you push to GitHub? I'm still seeing the old commits....

**Comment by mschuene** [comment]
ups, i pushed it now

**Comment by mikera** [comment]
Look good, thanks!

**Pull request merged**
