### PR TITLE
fixed slice behaviour for 1-d arrays

### PR DESCRIPTION
**Pull request by mschuene**
Fixed slice behaviour on 1d-arrays 
- in the default implementation
- for NDArray 
- added tests for it
- enforce it with tests in compliance test
  Build currently fails as the vectorz implementation also shows the bug. See https://github.com/mikera/vectorz/issues/21

### CODE REVIEW

**Comment by mikera** [comment]
Hi Maik, this looks sensible though PRs need to pass tests - I don't merge anything with failing tests.

If something unrelated fails, maybe comment out the offending test until it is fixed?

**Comment by mikera** [comment]
OK the latest vectorz-clj should now have a fix for this. Can you re-test?

**Comment by mschuene** [comment]
pulled from upstream. Should work fine now

**Comment by mikera** [comment]
Looks good, thanks!

**Pull request merged**
