### PR TITLE
Add default matrix-multiply for two vectors

### PR DESCRIPTION
**Pull request by farrellm**
Currently, default implementations of matrix-multiply are provided for all combinations of scalars, vectors, and matrices except for two vectors. This adds the default implementation for two vectors, which is vector-dot.

### CODE REVIEW

**Comment by mikera** [comment]
Thanks, this looks sensible.

Do you have a Clojure CA? I can merge if you have submitted one. We need this because core.matrix is intended to eventually become part of Clojure Contrib.

See:
http://clojure.org/contributing

**Comment by farrellm** [comment]
No, I'm afraid not. I'll send it out Monday and update you when it clears.

**Comment by mikera** [comment]
OK, thanks!

**Comment by mikera** [comment]
Hi @farrellm did you sent out the CA?

**Comment by farrellm** [comment]
Sorry for the delay; I mailed it today.

**Comment by mikera** [comment]
OK Cool - I'll merge it in, n the assumption that you will soon appear on the Clojure conttributors list!

**Pull request merged**
