### PR TITLE
Bug in the function 'diagonal'.

### PR DESCRIPTION
**Pull request by prasant94**
I found a bug in the function 'diagonal'.

### CODE REVIEW

**Comment by mikera** [comment]
Looks good, thanks. We probably need to review the docs on diagonal / main-diagonal and make sure everything is consistent

**Comment by mikera** [comment]
P.S. can you send in a Clojure CA? We need this for all your contributions since we ultimately want to move clore.matrix to clojure contrib.

see: http://clojure.org/contributing

**Comment by prasant94** [comment]
Is there a way to send a soft copy of the CA via an electronic medium?

**Comment by mikera** [comment]
I don't think so: they need a paper copy last time I remember.

**Comment by prasant94** [comment]
Ok.
Also, IF I get the GSoC internship, will I have to send a separate CA?

**Comment by mikera** [comment]
It's just one CA, and it covers everything Clojure related. So you only need to do it once!

**Pull request merged**
