### PR TITLE
Clean up ns declarations, more idiomatic code

### PR DESCRIPTION
**Pull request by danielcompton**
This cleans up the namespaces, converting :uses to :requires, removing unused declarations, and making code more idiomatic.

### CODE REVIEW

**Comment by mikera** [comment]
Looks generally good - thanks for taking a stab at cleanup!

One question: where you have replaced numerical comparisons with `pos?`, `zero?` etc. have you benchmarked to verify that this doesn't cause a performance overhead? We _really_ need to make sure this stuff gets properly inlined.....

**Comment by danielcompton** [comment]
That's something I need to check still. I'm pretty sure it does but need to verify.

**Comment by danielcompton** [comment]
They look equivalent https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/Numbers.java#L447 but I'll need to verify still.

**Comment by danielcompton** [comment]
These look equivalent in timings to me, 

```
(criterium.core/bench (< 0 5))
Evaluation count : 7315776000 in 60 samples of 121929600 calls.
             Execution time mean : 5.157079 ns
    Execution time std-deviation : 0.109501 ns
   Execution time lower quantile : 4.969851 ns ( 2.5%)
   Execution time upper quantile : 5.416292 ns (97.5%)
                   Overhead used : 3.037786 ns

Found 2 outliers in 60 samples (3.3333 %)
    low-severe   2 (3.3333 %)
 Variance from outliers : 9.4224 % Variance is slightly inflated by outliers
=> nil
(criterium.core/bench (pos? 5))
Evaluation count : 7502270520 in 60 samples of 125037842 calls.
             Execution time mean : 5.210669 ns
    Execution time std-deviation : 0.230549 ns
   Execution time lower quantile : 4.995326 ns ( 2.5%)
   Execution time upper quantile : 5.671237 ns (97.5%)
                   Overhead used : 3.037786 ns

Found 7 outliers in 60 samples (11.6667 %)
    low-severe   6 (10.0000 %)
    low-mild     1 (1.6667 %)
 Variance from outliers : 30.3327 % Variance is moderately inflated by outliers
=> nil
```

In the source:

``` java
static public boolean lt(double x, double y){
    return x < y;
}

static public boolean lte(double x, double y){
    return x <= y;
}

static public boolean gt(double x, double y){
    return x > y;
}

static public boolean gte(double x, double y){
    return x >= y;
}

static public boolean isPos(double x){
    return x > 0;
}

static public boolean isNeg(double x){
    return x < 0;
}

static public boolean isZero(double x){
    return x == 0;
}
```

so they are exactly equivalent.

**Comment by danielcompton** [comment]
This is ready for review now.

**Comment by mikera** [comment]
OK looks good, merging it in!

**Pull request merged**
