### PR TITLE
Updated project.clj from pom.xml

### PR DESCRIPTION
**Pull request by mars0i**

### CODE REVIEW

**Comment by mars0i** [comment]
I thought I could have two pull requests, one for the project.clj update, and the other for immutable-matrix for persistent-vector, but I forgot that github will just add all new commits into the same pull request.  But maybe they're both trivial enough that it doesn't matter.  The immutable-matrix implementation fixes new issue #135 for persistent-vector.  I took a look at ndarray, too, but didn't see what the right way to implement immutable-matrix was, and didn't have time to work through things to figure it out.

**Comment by mikera** [comment]
Looks good, thanks!

Hmmm... we may also need to handle the case where the persistent vector has nested mutable arrays inside it.....

**Comment by mars0i** [comment]
Interesting point.  I didn't think about the fact that persistent-vector can have other things inside, and didn't know that the result could count as a legitimate core.matrix matrix.  I see now that that works, and that it's possible to modify the matrix by accessing the mutable submatrix.

**Comment by mikera** [comment]
Yeah - it's slightly odd behaviour. I'm not sure if should even be encouraged.... but it works....

**Pull request merged**
