### PR TITLE
Adds  #'sum to API

### PR DESCRIPTION
**Pull request by bmabey**
In order to flesh out the API more I'm using it to implement some common machine learning metrics.  The first hiccup I ran into was that `sum` was not part of the API.  I added it along with the corresponding protocol and default implementation for the persistent vector.

I did consider just making a single implementation as `(m/ereduce m/add m)` defined in `core.clj` but I didn't know if that would be appropriate for all matrix types.  It seems like it would though so I could revert these changes and go with that instead.  What do you think?

BTW, any chance I could convince you to drop clojure.test and use midje instead?  Midje tests are far easier to read and write IMO and double as a nice form of documentation.

### CODE REVIEW

**Comment by mikera** [comment]
Hey Ben just getting back on your comment regarding midge.

The main reasons I use clojure.test:
- It's one less dependency
- People know it
- I like using cljunit for easy JUnit integration (https://github.com/mikera/cljunit)

I'm not familiar with Midge but if people prefer midge tests and they can still be made to work with cljunit then I'm happy to incorporate midge tests as well

**Comment by mikera** [comment]
Also:

`(ereduce + m)`

Is the best way of implementing sum for generic matrices I think. I've added this as a reasonable default implementation for java.lang.Object in core.matrix in the event that an implementation doesn't define PSummable

**Comment by bmabey** [comment]
Why not m/add? That way as long as the type has implemented add then they get sum for free? 

-Ben

**Comment by mjwillson** [comment]
A slight generalisation might be nice for the API around these kind of reduction-style operations -- it's nice (especially with sum) to be able to specify which axes to sum over. So the `sum` you're proposing would (IIUC) sum over all dimensions, but it's equally useful to sum over rows and get a vector of row sums, or similarly for columns -- and this generalises quite naturally to an NDArray context too.

http://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html might serve as an example (although I think only lets you sum over all elements, or over a single axis)

**Comment by bmabey** [comment]
I like the idea of being able to sum across a specified dimension with the default being all the elements.

Any preference on what the sum API signature should be in that case? Just have an optional second argument be the dimension to sum over?

**Comment by mjwillson** [comment]
That sounds good yeah. I wonder if it makes sense to build this generality into `ereduce` too so any reduction could benefit?

(By the way, one thing to bear in mind with ereduce over all entries / over more than one dimension, is that we should document and ensure implementations are consistent about the operation order, since the results will depend on it when reducing with non-commutative or non-associative operations: e.g. `(a_11 * ... * a_1n) * ... * (a_m1 * ... * a_mn)` vs the other way round for an operator `*`.)

**Comment by mjwillson** [comment]
I guess one advantage of reducing over one dimension at a time is that you're forced to make this ordering explicit... but of course doesn't matter for `sum`, or element-wise product or anything else commutative.

**Comment by heffalump** [comment]
I'm much more interested in being able to ereduce over a specific dimension than to have sum do that.  I mean, I suppose sum is a nice convenience, but a souped-up ereduce could do all that and more.

**Comment by mikera** [comment]
The advantage of `sum` is that it is very useful for a few important cases (e.g. normalising a probability vector so that all probabilities add up to one). I think it is worth including in the API on those grounds alone.

As for a more general sum / reduce over arbitrary dimensions, I'm all for that too but can we discuss on list rather than in a close pull request issue? I think it needs a slightly broader design discussion....

**Pull request merged**
