### PR TITLE
new-matrix bug with dataset implementation fixed

### PR DESCRIPTION
**Pull request by Gerrrr**
Bug:

``` Clojure
user=> (new-matrix :dataset 3 4)
#clojure.core.matrix.impl.dataset.DataSet{:column-names [nil nil nil nil], :columns [[0.0 0.0 0.0] [0.0 0.0 0.0] [0.0 0.0 0.0] [0.0 0.0 0.0]]}
```

After applying PR:

``` Clojure
user=> (new-matrix :dataset 3 4)
#clojure.core.matrix.impl.dataset.DataSet{:column-names [:0 :1 :2 :3], :columns [[0.0 0.0 0.0] [0.0 0.0 0.0] [0.0 0.0 0.0] [0.0 0.0 0.0]]}
```

### CODE REVIEW

**Comment by mikera** [comment]
Hmmm.... do you think that is a bug?

`nil` might be a better column name if nothing is specified? 

or what about `:a` `:b` `:c` etc. like in a spreadsheet?

**Comment by Gerrrr** [comment]
I actually thought that this might be a bug because I haven't seen this way of getting vector of `nil`s before.
Personally, I think that `:a` `:b` `:c` is better idea.

**Comment by mikera** [comment]
We could also use 0 ,1, 2.... which would be valid indices as well as row names....

Think this is one to ask the Numerical Clojure / Incanter groups? Someone may have a smart idea

**Comment by Gerrrr** [comment]
Changed according to discussion in Google groups.

**Comment by mikera** [comment]
Looks like you have some merge conflicts to resolve?

**Pull request merged**
