### PR TITLE
e== bug related to equality dependence on order of args fixed

### PR DESCRIPTION
**Pull request by Gerrrr**
Bug demo:

``` Clojure
user=> m1
[6.0 15.0 24.0 33.0]
user=> m2
 A 1x4 matrix
 -------------
 6.00e+00  1.50e+01  2.40e+01  3.30e+01

user=> (e== m1 m2)
false
user=> (e== m2 m1)
true
```

### CODE REVIEW

**Comment by mikera** [comment]
Hmmm...... clearly this is a bug if the comparison is order-dependent. 

But the API needs careful thought here. What should be the result if arrays have different shape? Arguably `e==` should be false for arrays with different shape.

A good analogy is nested Clojure vectors: is `[1 2 3 4]` equal to `[[1 2] [3 4]]`?

**Comment by mikera** [comment]
Note comparable docstring for `equals`:

"Returns true if two arrays are numerically equal.

   Will return false for arrays of different shapes.

   May either return false or throw an error if the arrays are not numerical.

   If epsilon is provided, performs an equality test
   with the given maximum tolerance (default is 0.0, i.e. exact numerical equivalence)"

**Comment by Gerrrr** [comment]
Thanks for the detailed feedback. I think you are right.
Then, clatrix implementaion of `PMatrixEquality` is wrong. In particular, I suppose that the bug located here - https://github.com/tel/clatrix/blob/master/src/clatrix/core.clj#L1422
Everything considered as 1 dimensional is put into vector (instead of converting to vector with `vec`, I suppose).

**Comment by mikera** [comment]
Yeah, Incanter is a bit strange in its treatment of matrices... it tends to prefer using Nx1 or 1xN matrices instead of vectors (which I think is the result of copying R and MATLAB rather than smart design...).

In core.matrix we are much more consistent - everything is a n-dimensional array, which is much more like the NumPy approach. I think this is a much cleaner approach

To the extent that we want to maintain backwards compatibility, we'll probably be stuck with a bit of a compromise in the Incanter / core.matrix implementation. i.e. we may have to stick to Incanter conventions in the Incanter API, but it should be possible to emulate these behaviours with core.matrix pretty easily (since core.matrix supports a superset of operations)

Just giving you a heads up on some of the design issues to consider!

**Comment by Gerrrr** [comment]
Thanks for clarifications.
BTW, the initial issue seems to be fixed in clatrix master branch.

``` Clojure
;;Tested in clatrix master branch
user=> m1
[6.0 15.0 24.0 33.0]
user=> m2
 A 1x4 matrix
 -------------
 6.00e+00  1.50e+01  2.40e+01  3.30e+01

user=> (m/e== m1 m2)
false
user=> (m/e== m2 m1)
false
```

So, I suppose this PR is not relevant.

**Comment by mikera** [comment]
OK.... should we close this PR?

**Comment by alexott** [comment]
Maybe we should think about having 2 APIs in Incanter?

On Fri, May 30, 2014 at 4:30 PM, Mike Anderson notifications@github.com
wrote:

> Yeah, Incanter is a bit strange in its treatment of matrices... it tends
> to prefer using Nx1 or 1xN matrices instead of vectors (which I think is
> the result of copying R and MATLAB rather than smart design...).
> 
> In core.matrix we are much more consistent - everything is a n-dimensional
> array, which is much more like the NumPy approach. I think this is a much
> cleaner approach
> 
> To the extent that we want to maintain backwards compatibility, we'll
> probably be stuck with a bit of a compromise in the Incanter / core.matrix
> implementation. i.e. we may have to stick to Incanter conventions in the
> Incanter API, but it should be possible to emulate these behaviours with
> core.matrix pretty easily (since core.matrix supports a superset of
> operations)
> 
> Just giving you a heads up on some of the design issues to consider!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mikera/core.matrix/pull/151#issuecomment-44656976.

## 

With best wishes,                    Alex Ott
http://alexott.net/
Twitter: alexott_en (English), alexott (Russian)
Skype: alex.ott

**Comment by mikera** [comment]
Hi Alex,

We already have 2 APIs to an extent - we have both the core.matrix API and incanter.core API. They should both work on the same matrix types and should be interoperable. 

The semantics for some operations are slightly different because of the way dimensions are handled. This is annoying in places but manageable overall I think... and Incanter 2.0 offers an opportunity to harmonise some things. 

The main thing we have to do is to be very clear in docs where we have differences (and be clear why).

 Mike.

**Comment by mikera** [comment]
Closing this PR as it seems to be a non-issue for core.matrix

**Pull request closed without merging**
