### PR TITLE
#40 Add elementary row operations

### PR DESCRIPTION
**Pull request by munk**
I have added row_operators.clj and test_row_operators.clj.

The contribution is three functions for elementary row operations:

**(swap [X i j]**
    swaps row i with row j

**(multiply [X i k])**
    multiply row i by k

**(add [X i j k])**
    add row j times k to row i

### CODE REVIEW

**Comment by mikera** [comment]
Hi John,

Thanks for taking a stab at this!

In principle this looks good, however there are a few things that need to be addressed before we can merge this:
1. Can you make pull requests against `develop` rather than `master`? master is for released versions (as per the git-flow convention)  
2. Can you sign and send off a Clojure CLA? We need to have a CLA for all core.matrix contributors, because the code will eventually get merged into Clojure Contrib
3. Your code looks like it is specialised for Clojure vectors - core.matrix operation is a bit more complex than that, because we support multiple different matrix implementations: what we need to do is have the functions call a protocol that can be implemented for any matrix class. Then your code can become the implementation for IPersistentVector (see clojure/core/matrix/impl/persistent_vector.clj for examples of this)
4. There also should be a "default" implementation that gets used for matrix classes that don't directly implement the elementary row operation protocol(s). These need to be written in terms of the other more fundamental protocols (see clojure/core/matrix/impl/default.clj for examples of this)
5. The functions should probably be in the main `clojure.core.matrix` namespace. The functions also probably need to be renamed to make it clear they are row operations - perhaps `swap-rows`, `add-row` and `multiply-row`?

**Comment by mikera** [comment]
Hi @jdowns - are you planning to take a stab at addressing the outstanding issues related to this PR?

No problem if not, just let me know so I can close it.....

**Comment by munk** [comment]
@mikera I would like to finish this.  It's been on my back burner for awhile but I didn't realize how long it was!  I'll see if I can get the issues addressed soon.

**Comment by mikera** [comment]
OK thanks, just checking! I had a couple of people ask for these so I was going to add them myself if you weren't able to.....

**Comment by munk** [comment]
@mikera  I think I'm finished, but I'm not sure how to test the default implementation.  I tried adding tests to the compliance tester, but it complains that the other implementations don't have PRowOperations implemented.  

Is there something I'm missing to get it to fall through to the default, or am I testing this the wrong way?  Ultimately I want to see that all the matrix classes that don't implement the row operations fall through to the default and work correctly.

My other question is - I don't see how to change this pull request to `develop`.  Should I make a different pull request against that branch and close this one?

**Comment by mikera** [comment]
Awesome! It looks good.

The way to make the default implementation work (i.e. for java.lang.Object) is to write some code that implements the operation using _only_ the core.matrix protocols. A trick you can use is to coerce to persistent vectors first so that your existing persistent vector implementation gets used, e.g. something like 

`(mp/swap-rows (mp/coerce-param [] m) i j)`

This obviously isn't very efficient, but it should be enough to get the default implementation working and passing tests, which is the main objective.

I'm not actually sure how to switch the PR to a different branch. If nothing else works, then it's no problem to just create a new one (but do reference this PR for the history!)

**Pull request closed without merging**
