### PR TITLE
add more misc numeric tests based on Householder matrix

### PR DESCRIPTION
**Pull request by fbmnds**
Ref. comment below.

### CODE REVIEW

**Comment by mikera** [comment]
Got a few things failing here in the Travis CI build. @si14 Looks like the lack of an inverse implementation in NDArray is one of the problems?

**Comment by fbmnds** [comment]
This pr is depricated. I updated it based on yesterday´s current development status. Currently, only 'vectorz' is the only implementation to pass fully, 'persistent-vector' passes except matrix invertation.

**Comment by si14** [comment]
@mikera indeed it is. However, the lack of inverse in default.clj is worse, because we are breaking "you need only mandatory protocols" contract here. I'll check it.

**Comment by mikera** [comment]
Yeah I think the best way to do a default implementation is to use the inverse calculation from NDArray. I had a quick  look at implementing inverse with persistent vectors but it seemed like a pretty bad idea from a performance perspective - you really want mutable matrices here.

If we could get a working default implementation for some of the decompositions that would be even better of course - these provide even better ways to compute the inverse of an arbitrary matrix.

**Pull request closed without merging**
