### PR TITLE
Implemented order

### PR DESCRIPTION
**Pull request by Gerrrr**
Implementation of https://github.com/mikera/core.matrix/issues/84

Some examples:

``` clojure
(order [:a :b :c :d] [0 2 2])
=> [:a :c :c]
```

``` clojure
(order [[:a :b :c]
        [:e :f :g]] 1 [1 2])
=> [[:b :f] [:c :g]]
```

### CODE REVIEW

**Comment by mikera** [comment]
Look great, thanks!

This needs a couple more things to be fully complete:
- A default implementation in default.clj (this will get called for matrix implementations that don't directly implement `POrder`). This should enable `order` to work out-of-the-box on vectorz-clj and Clatrix for example.
- A compliance test (i.e. the test suite that other implementations can call to test that the `order` function is working correctly for their implementation. see: https://github.com/mikera/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix/compliance_tester.clj )

Also - do you have a Clojure CA? We need one in order to be able to accept contributions.... see: 

http://clojure.org/contributing

**Comment by mikera** [comment]
I will merge this since it is an improvement over what we currently have.

But would be great if you could send off the CA as soon as possible! Otherwise we'll need to revert your changes, which is no fun for anyone :-)

**Comment by Gerrrr** [comment]
Thanks for the feedback, I will implement things you proposed.
CA is on its way to NC :-)

**Comment by mikera** [comment]
Awesome, thanks!

**Pull request merged**
