### PR TITLE
Implement 2D Java double array

### PR DESCRIPTION
**Pull request by fyquah**
https://github.com/mikera/core.matrix/issues/247

### CODE REVIEW

**Comment by mikera** [comment]
Looks good, thanks for working on this!

One point I think would be useful to change before we merge: I think the implementation key should be `:double-array`, i.e. the same as for 1D arrays. The constructor functions should be able to examine their arguments to construct the right array type.

This is because:
- It is consistent with other implementations
- It helps people to write more generic code that can handle arrays of different shapes

**Comment by fyquah** [comment]
I have addressed those issues with https://github.com/fyquah95/core.matrix/commit/acfef31e0c323a45d2ac790de2000f91baa03bbd

There is still two problems with the implementation though:
- https://github.com/fyquah95/core.matrix/blob/develop/src/main/clojure/clojure/core/matrix/impl/double_array.clj#L149 I commented out the code which breaks some test cases. This is not too much of a problem in my opinion - the default implementation works quite fine
- I am assuming the all columns are of equal length (true for a matrix in a mathematical sense). Is this assumption okay?

**Comment by fyquah** [comment]
On a side note, is there any benchmarking tools in core.matrix? (i.e.: some sort of function / macro i can call to generate the run time for some of the core functions)

**Comment by mikera** [comment]
Thanks! I'll merge this and run a few tests myself.

The assumption of equal column lengths is OK. It's the user's responsibility to pass a valid argument (although it is nice to validate and throw errors where we can, and where there is not a significant performance impact for doing so)

**Comment by mikera** [comment]
@fyquah95 There was some work on a mini benchmarking suite here:

https://github.com/mikera/core.matrix/tree/develop/src/dev/clojure/clojure/core/matrix/docgen

Not tried running it recently, but you may want to try it out?

**Comment by fyquah** [comment]
It didn't work for me (for something to do with `unresolved var dyn-args` ), I made a simple patch that should fix the problem https://github.com/fyquah95/core.matrix/commit/304716be461fb9146179dfc8aa6da7260a32b3ff .

**Comment by mikera** [comment]
It's pretty old code - if you can send me a PR that would be great! @si14 originally wrote it and the original intention was to build a performance comparison chart that could be put on a webpage. 

See:
http://mikera.github.io/core.matrix/bench.html

**Pull request merged**
