### PR TITLE
Adding commons-math to KNOWN-IMPLEMENTATIONS

### PR DESCRIPTION
**Pull request by adereth**
I needed to use some of the more esoteric decompositions available in Apache Commons Math.  I really liked the interface provided by core.matrix and I wanted to learn more about Clojure's protocols, so I went ahead and tried adding support.

Following your instructions in the Implementation Guide, I've added it to the KNOWN-IMPLEMENTATIONS map.

I'd appreciate any feedback you have on my implementation.  Thanks!

### CODE REVIEW

**Comment by mikera** [comment]
Great stuff - would be awesome to have a commons math implementation for core.matrix

Can you give me a link to your implementation repo? Happy to add it to the core.matrix Wiki

I'll accept this pull request (since all it does is add to the known implementations). Happy to review your main implementation repo as well if you send through the link.

**Comment by mikera** [comment]
P.S. it would be good to add the "more esoteric decompositions" to the `core.matrix` top level API at some point. Which ones in particular did you need?

**Comment by adereth** [comment]
I see you already found the implementation, but it's at [Adereth/apache-commons-matrix](https://github.com/Adereth/apache-commons-matrix) for anyone else following along.

These are the decompositions that I've needed:
- [Eigen](http://commons.apache.org/proper/commons-math/javadocs/api-3.2/org/apache/commons/math3/linear/EigenDecomposition.html)
- [LU](http://commons.apache.org/proper/commons-math/javadocs/api-3.2/org/apache/commons/math3/linear/LUDecomposition.html)
- [QR](http://commons.apache.org/proper/commons-math/javadocs/api-3.2/org/apache/commons/math3/linear/QRDecomposition.html)

The other decompositions that are provided that you might consider eventually supporting are:
- [Cholesky](http://commons.apache.org/proper/commons-math/javadocs/api-3.2/org/apache/commons/math3/linear/CholeskyDecomposition.html)
- [Rectangular Cholesky](http://commons.apache.org/proper/commons-math/javadocs/api-3.2/org/apache/commons/math3/linear/RectangularCholeskyDecomposition.html)
- [Rank Revealing QR](http://commons.apache.org/proper/commons-math/javadocs/api-3.2/org/apache/commons/math3/linear/RRQRDecomposition.html)
- [Singular Value](http://commons.apache.org/proper/commons-math/javadocs/api-3.2/org/apache/commons/math3/linear/SingularValueDecomposition.html)

I now see that you already have these planned based on [the skeleton functions under linear algebra algorithms](https://github.com/mikera/matrix-api/blob/master/src/main/clojure/clojure/core/matrix.clj#L929).

**Comment by mikera** [comment]
Great, thanks for the info, always great to know what people are using! @si14 added LU decomposition to the core.matrix NDArray, but we haven't wired up the API function yet

**Pull request merged**
