### PR TITLE
Fix #270 - Remove mul and mul!

### LINKED ISSUE #270: Are mul and emul both needed?
The only difference seems to be that emul is not guantanteed to work with a scalar as second argument.

Are both functions needed? If for performance reasons, then should e.g. the add function also have an e-add counterpart?

### PR DESCRIPTION
**Pull request by avgerin0s**
Fixes #270

### CODE REVIEW

**Comment by mikera** [comment]
Hmmm looks good but can you leave the `emul` and `emul!` functions in place but with `:deprecated` metadata and comments for the moment?

Want to be able to give people time to transition before we delete these entirely, as it will break existing code....

**Comment by avgerin0s** [comment]
@mikera I see, thanks, I'll update the PR asap :)

**Comment by avgerin0s** [comment]
Replaced removal with deprecation

**Comment by mikera** [comment]
Looks good, thanks!

**Pull request merged**
