### PR TITLE
Add codox documentation

### LINKED ISSUE #208: Add core.matrix API docs
I looked around and couldn't find generated API docs for core.matrix anywhere. Would it be possible to generate them and host them somewhere? GitHub pages might be a good option. If they do exist then can we add links to them from the README and main wiki page?

### PR DESCRIPTION
**Pull request by danielcompton**
You generate the docs by running `lein doc`. To push them to GitHub, follow the instructions at https://github.com/weavejester/codox/wiki/Deploying-to-GitHub-Pages

Fixes #208.

I made a new profile for this because of https://github.com/weavejester/codox/issues/58

### CODE REVIEW

**Comment by mikera** [comment]
OK I tried this but still having some issues. Maybe it's a Windows thing - does it work for you? @danielcompton

**Comment by danielcompton** [comment]
Yeah it works fine for me on Mac OS X. I'll have a go on a Windows machine.

**Comment by danielcompton** [comment]
I don't actually have a Windows machine handy. Do you have a unix machine to generate the docs on?

**Comment by mikera** [comment]
I can find one :-) will try it out when I get a chance

**Comment by mschuene** [comment]
doesn't work for me on ubuntu 14.04 either
first I added the codox plugin to the project.clj file, because I didn't have it in my profiles and lein could not find the doc command without. I think it is a good idea to include it in the project.clj so that this doesn't happen or there are strange results when a different codox version is used by one developer.

afterwards, running lein docs gives me this stacktrace
lein clean && lein doc
(Retrieving net/mikera/vectorz-clj/0.23.0/vectorz-clj-0.23.0.pom from clojars)
(Retrieving net/mikera/vectorz/0.36.0/vectorz-0.36.0.pom from central)
(Retrieving net/mikera/core.matrix/0.26.0/core.matrix-0.26.0.pom from clojars)
(Retrieving net/mikera/clojure-utils/0.6.0/clojure-utils-0.6.0.pom from clojars)
(Retrieving net/mikera/vectorz/0.36.0/vectorz-0.36.0.jar from central)
(Retrieving net/mikera/core.matrix/0.26.0/core.matrix-0.26.0.jar from clojars)
(Retrieving net/mikera/vectorz-clj/0.23.0/vectorz-clj-0.23.0.jar from clojars)
(Retrieving net/mikera/clojure-utils/0.6.0/clojure-utils-0.6.0.jar from clojars)
Compiling 3 source files to /home/kima/programming/core.matrix/target/classes
warning: Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '1.8'
1 warning
Exception in thread "main" java.lang.Exception: Could not load codox writer codox.writer.html, compiling:(/tmp/form-init10053507744937932.clj:1:88)
    at clojure.lang.Compiler.load(Compiler.java:7142)
    at clojure.lang.Compiler.loadFile(Compiler.java:7086)
    at clojure.main$load_script.invoke(main.clj:274)
    at clojure.main$init_opt.invoke(main.clj:279)
    at clojure.main$initialize.invoke(main.clj:307)
    at clojure.main$null_opt.invoke(main.clj:342)
    at clojure.main$main.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Could not load codox writer codox.writer.html
    at codox.main$writer$fn__227.invoke(main.clj:13)
    at codox.main$writer.invoke(main.clj:9)
    at codox.main$generate_docs.invoke(main.clj:74)
    at user$eval291.invoke(form-init10053507744937932.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6693)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    ... 11 more
Caused by: java.lang.reflect.InvocationTargetException, compiling:(html.clj:29:1)
    at clojure.lang.Compiler$DefExpr.eval(Compiler.java:430)
    at clojure.lang.Compiler.eval(Compiler.java:6708)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5066.invoke(core.clj:5641)
    at clojure.core$load.doInvoke(core.clj:5640)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5446)
    at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
    at clojure.core$load_lib.doInvoke(core.clj:5485)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$load_libs.doInvoke(core.clj:5524)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$require.doInvoke(core.clj:5607)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at codox.main$writer$fn__227.invoke(main.clj:10)
    ... 17 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at clojure.lang.Compiler$NewExpr.eval(Compiler.java:2484)
    at clojure.lang.Compiler$DefExpr.eval(Compiler.java:417)
    ... 37 more
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
    at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
    at org.parboiled.Parboiled.createParser(Parboiled.java:54)
    at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
    at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:71)
    ... 43 more
Subprocess failed

**Comment by danielcompton** [comment]
@mschuene are you running off develop? You shouldn't need to add the Codox as its already in core.matrix's project.clj. Codox interacts badly with hiccup so I put it in a separate profile. Running lein doc is actually an alias to run with-profile doc lein doc.

**Comment by mschuene** [comment]
@danielcompton yea, you were right, i checked out upstream/develop from my core.matrix fork but somehow if didn't reach the latest state.
But even when I checkout the current develop branch and I see that codox is in project.clj and the lein doc alias, there is still the following error when I run lein doc
lein clean && lein doc
Compiling 3 source files to /home/kima/programming/core.matrix/target/classes
Compiling clojure.core.matrix.impl.ndarray-double
Compiling clojure.core.matrix.impl.ndarray-object
Exception in thread "main" java.lang.Exception: Could not load codox writer codox.writer.html, compiling:(/tmp/form-init7453703079383640536.clj:1:90)
    at clojure.lang.Compiler.load(Compiler.java:7142)
    at clojure.lang.Compiler.loadFile(Compiler.java:7086)
    at clojure.main$load_script.invoke(main.clj:274)
    at clojure.main$init_opt.invoke(main.clj:279)
    at clojure.main$initialize.invoke(main.clj:307)
    at clojure.main$null_opt.invoke(main.clj:342)
    at clojure.main$main.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Could not load codox writer codox.writer.html
    at codox.main$writer$fn__227.invoke(main.clj:13)
    at codox.main$writer.invoke(main.clj:9)
    at codox.main$generate_docs.invoke(main.clj:61)
    at user$eval290.invoke(form-init7453703079383640536.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6693)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    ... 11 more
Caused by: java.lang.reflect.InvocationTargetException, compiling:(html.clj:29:1)
    at clojure.lang.Compiler$DefExpr.eval(Compiler.java:430)
    at clojure.lang.Compiler.eval(Compiler.java:6708)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    at clojure.lang.RT.loadResourceScript(RT.java:370)
    at clojure.lang.RT.loadResourceScript(RT.java:361)
    at clojure.lang.RT.load(RT.java:440)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5066.invoke(core.clj:5641)
    at clojure.core$load.doInvoke(core.clj:5640)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5446)
    at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
    at clojure.core$load_lib.doInvoke(core.clj:5485)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$load_libs.doInvoke(core.clj:5524)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:626)
    at clojure.core$require.doInvoke(core.clj:5607)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at codox.main$writer$fn__227.invoke(main.clj:10)
    ... 17 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at clojure.lang.Compiler$NewExpr.eval(Compiler.java:2484)
    at clojure.lang.Compiler$DefExpr.eval(Compiler.java:417)
    ... 37 more
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
    at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
    at org.parboiled.Parboiled.createParser(Parboiled.java:54)
    at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
    at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:71)
    ... 43 more
Error encountered performing task 'doc' with profile(s): 'doc'
Subprocess failed

**Comment by mikera** [comment]
That's pretty much the same error as I get on Windows. So guess it isn't a Windows thing?

**Comment by danielcompton** [comment]
Can you try running it after removing hiccup? Also, could you put the stack traces in a gist? Thanks

**Pull request merged**
