### PR TITLE
[WIP] Feature transpose dim ordering

### PR DESCRIPTION
**Pull request by AlejandroCatalina**
Transposing given a certain axes ordering is provided.

Any more tests to add and suggestions or improvements to implementation, please say it.

Some tests failed in travis, i'm reviewing it.

### CODE REVIEW

**Comment by mikera** [comment]
Should probably add in validation that the ordering vector is the same length as the dimensionality of the array - throw an error if not (I don't think transpose without a full ordering makes logical sense?)

**Comment by mikera** [comment]
I don't think your implementation is right yet - in particular don't see how you can implement transpose just using reshape, since that will mess up all the element orderings

I think the right strategy is something like as follows:
1) Take the slices of the array from the first dimension selected in the ordering
2) Transpose each, recursively, using the remainder of the ordering (might have to re-number dims)
3) Concatenate the results to create the final transposed array

**Comment by AlejandroCatalina** [comment]
I've been actually taking Numpy as my model and its implementation just reorders the axes, which is what reshape basically does. For what I've seen in Numpy, transpose and axes ordering is transpose + reshape given the new order of the original axes. I have tested it with many examples in both clojure and numpy. 

My implementation may be not right yet, indeed. I'll give a try at your description which seems to be essentially the same. 

I'll add that condition, I think you're right and that wouldn't make logical sense. Thank you for your guidance here, and sorry if this is being too much trouble for you.

**Comment by mikera** [comment]
Not at all - no need to thank me, your contributions are very welcome!

**Comment by AlejandroCatalina** [comment]
I've been playing with this for a while and i keep getting the same results, any new ideas or thoughts?

**Comment by mikera** [comment]
I think this is now complete in the latest release

**Pull request closed without merging**
