### PR TITLE
add support for negative indizes for the select functionality

### PR DESCRIPTION
**Pull request by mschuene**
docstrings updated and test cases added.

### CODE REVIEW

**Comment by mikera** [comment]
Not sure about negative indices - What's the big motivation?

I'm generally suspicious of overloading functionality like this in core functionality: it's usually better to keep things simple and let users wrap with more sophisticated functionality if they need it.

**Comment by mschuene** [comment]
the same motivation like having :all etc, for convenience. 
Python people attracted by clojure for example would miss this functionality. 
From the recent thread on the clojure mailing list, I guess that this "feature" is wanted, and it doesn't complicate things much.

**Comment by mikera** [comment]
Hmmm but it potentially masks bugs: when you are computing array indices then wrapping round can make a mis-computed index appear to work when in fact it is using invalid data (think off-by-one errors?)

I'm not particularly worried about performance in `select` since it is more of a convenience function anyway.

If we are going to do this, I think it should do a proper modulo operation so that we get unlimited wrap-around

**Comment by mikera** [comment]
@mschuene can you do a straw poll on Numerical Clojure / Incnter lists? Guess I'm happy to include if there is general support.

We should also think about allowing dimension labels here as well, I guess :-)

**Comment by mikera** [comment]
Comments on this PR if it is to be included:
- Index should be computed with a modulo function
- We should move the selector specific functionality out to the c.c.m.select namespace. I want to keep the main c.c.m namespace pretty clean and free of implementation details.
- The normalisation function should probably be a macro so that it gets properly inlined for performance

**Comment by mikera** [comment]
Closing for the moment as there doesn't seem to be any consensus / demand to get this in. @mschuene feel free to reopen if that changes!

**Pull request closed without merging**
